# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empanswerslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empmailid', models.CharField(max_length=50)),
                ('empqueid', models.IntegerField()),
                ('empanswer', models.CharField(max_length=5)),
                ('originalanswer', models.CharField(max_length=5)),
                ('emptech', models.CharField(max_length=20)),
                ('testid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('ro', models.CharField(max_length=2)),
                ('subtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Techlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=30)),
                ('timelimit', models.IntegerField()),
                ('status', models.CharField(default='Deactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('tech', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
